// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxqruxwaqmokirlmkmxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4cXJ1eHdhcW1va2lybG1rbXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTU2NDYsImV4cCI6MjA1ODQ5MTY0Nn0.GtTkzC3YwY0ZSY9rPEQPN_PWUyM3BHx2xcvB0Wg61kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);